[2025-06-28T13:02:09.137+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: amazon_reviews_raw_data_ingestion.data_loading manual__2025-06-28T13:02:01.603906+00:00 [queued]>
[2025-06-28T13:02:09.157+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: amazon_reviews_raw_data_ingestion.data_loading manual__2025-06-28T13:02:01.603906+00:00 [queued]>
[2025-06-28T13:02:09.158+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-06-28T13:02:09.191+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): data_loading> on 2025-06-28 13:02:01.603906+00:00
[2025-06-28T13:02:09.222+0000] {standard_task_runner.py:57} INFO - Started process 1387 to run task
[2025-06-28T13:02:09.240+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'amazon_reviews_raw_data_ingestion', 'data_loading', 'manual__2025-06-28T13:02:01.603906+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/jet_***_app.py', '--cfg-path', '/tmp/tmp4p_j14h_']
[2025-06-28T13:02:09.278+0000] {standard_task_runner.py:85} INFO - Job 27: Subtask data_loading
[2025-06-28T13:02:09.451+0000] {task_command.py:416} INFO - Running <TaskInstance: amazon_reviews_raw_data_ingestion.data_loading manual__2025-06-28T13:02:01.603906+00:00 [running]> on host a2bf817b2ea7
[2025-06-28T13:02:09.687+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='amazon_reviews_raw_data_ingestion' AIRFLOW_CTX_TASK_ID='data_loading' AIRFLOW_CTX_EXECUTION_DATE='2025-06-28T13:02:01.603906+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-28T13:02:01.603906+00:00'
[2025-06-28T13:02:09.708+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-28T13:02:09.716+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /Users/nfn8y/Desktop/Sukanya/JET/Assignment/utils/load_raw_data.py']
[2025-06-28T13:02:09.786+0000] {subprocess.py:86} INFO - Output:
[2025-06-28T13:02:10.441+0000] {subprocess.py:93} INFO - python3: can't open file '/Users/nfn8y/Desktop/Sukanya/JET/Assignment/utils/load_raw_data.py': [Errno 2] No such file or directory
[2025-06-28T13:02:10.455+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-06-28T13:02:10.547+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-06-28T13:02:10.566+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=amazon_reviews_raw_data_ingestion, task_id=data_loading, execution_date=20250628T130201, start_date=20250628T130209, end_date=20250628T130210
[2025-06-28T13:02:10.631+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 27 for task data_loading (Bash command failed. The command returned a non-zero exit code 2.; 1387)
[2025-06-28T13:02:10.676+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-06-28T13:02:10.809+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
