[2025-06-28T13:14:17.140+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: amazon_reviews_raw_data_ingestion.data_loading manual__2025-06-28T13:14:12.662708+00:00 [queued]>
[2025-06-28T13:14:17.166+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: amazon_reviews_raw_data_ingestion.data_loading manual__2025-06-28T13:14:12.662708+00:00 [queued]>
[2025-06-28T13:14:17.166+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-06-28T13:14:17.178+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): data_loading> on 2025-06-28 13:14:12.662708+00:00
[2025-06-28T13:14:17.201+0000] {standard_task_runner.py:57} INFO - Started process 82 to run task
[2025-06-28T13:14:17.212+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'amazon_reviews_raw_data_ingestion', 'data_loading', 'manual__2025-06-28T13:14:12.662708+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/jet_***_app.py', '--cfg-path', '/tmp/tmpc15ax81y']
[2025-06-28T13:14:17.255+0000] {standard_task_runner.py:85} INFO - Job 30: Subtask data_loading
[2025-06-28T13:14:17.349+0000] {task_command.py:416} INFO - Running <TaskInstance: amazon_reviews_raw_data_ingestion.data_loading manual__2025-06-28T13:14:12.662708+00:00 [running]> on host 1d392fc53e17
[2025-06-28T13:14:17.431+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='amazon_reviews_raw_data_ingestion' AIRFLOW_CTX_TASK_ID='data_loading' AIRFLOW_CTX_EXECUTION_DATE='2025-06-28T13:14:12.662708+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-28T13:14:12.662708+00:00'
[2025-06-28T13:14:17.437+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-28T13:14:17.438+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/utils/load_raw_data.py']
[2025-06-28T13:14:17.459+0000] {subprocess.py:86} INFO - Output:
[2025-06-28T13:14:18.341+0000] {subprocess.py:93} INFO - Starting raw data ingestion...
[2025-06-28T13:14:18.343+0000] {subprocess.py:93} INFO - Error connecting to the database: connection to server at "localhost" (::1), port 5432 failed: Connection refused
[2025-06-28T13:14:18.343+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-06-28T13:14:18.343+0000] {subprocess.py:93} INFO - connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
[2025-06-28T13:14:18.343+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-06-28T13:14:18.343+0000] {subprocess.py:93} INFO - 
[2025-06-28T13:14:18.343+0000] {subprocess.py:93} INFO - An error occurred during raw data loading: connection to server at "localhost" (::1), port 5432 failed: Connection refused
[2025-06-28T13:14:18.343+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-06-28T13:14:18.344+0000] {subprocess.py:93} INFO - connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
[2025-06-28T13:14:18.344+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-06-28T13:14:18.344+0000] {subprocess.py:93} INFO - 
[2025-06-28T13:14:18.394+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-28T13:14:18.439+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=amazon_reviews_raw_data_ingestion, task_id=data_loading, execution_date=20250628T131412, start_date=20250628T131417, end_date=20250628T131418
[2025-06-28T13:14:18.467+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-06-28T13:14:18.492+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
