[2025-06-29T10:14:15.569+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: amazon_reviews_raw_data_ingestion.data_loading manual__2025-06-29T10:14:12.394055+00:00 [queued]>
[2025-06-29T10:14:15.573+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: amazon_reviews_raw_data_ingestion.data_loading manual__2025-06-29T10:14:12.394055+00:00 [queued]>
[2025-06-29T10:14:15.573+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-06-29T10:14:15.579+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): data_loading> on 2025-06-29 10:14:12.394055+00:00
[2025-06-29T10:14:15.587+0000] {standard_task_runner.py:57} INFO - Started process 104 to run task
[2025-06-29T10:14:15.591+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'amazon_reviews_raw_data_ingestion', 'data_loading', 'manual__2025-06-29T10:14:12.394055+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/jet_***_app.py', '--cfg-path', '/tmp/tmp9quktomu']
[2025-06-29T10:14:15.594+0000] {standard_task_runner.py:85} INFO - Job 50: Subtask data_loading
[2025-06-29T10:14:15.623+0000] {task_command.py:416} INFO - Running <TaskInstance: amazon_reviews_raw_data_ingestion.data_loading manual__2025-06-29T10:14:12.394055+00:00 [running]> on host 7020de0dae0a
[2025-06-29T10:14:15.683+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='amazon_reviews_raw_data_ingestion' AIRFLOW_CTX_TASK_ID='data_loading' AIRFLOW_CTX_EXECUTION_DATE='2025-06-29T10:14:12.394055+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-29T10:14:12.394055+00:00'
[2025-06-29T10:14:15.686+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-29T10:14:15.687+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/utils/load_raw_data.py']
[2025-06-29T10:14:15.697+0000] {subprocess.py:86} INFO - Output:
[2025-06-29T10:14:16.353+0000] {subprocess.py:93} INFO - Starting raw data ingestion...
[2025-06-29T10:14:16.361+0000] {subprocess.py:93} INFO - Error connecting to the database: connection to server at "localhost" (::1), port 5432 failed: Connection refused
[2025-06-29T10:14:16.361+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-06-29T10:14:16.361+0000] {subprocess.py:93} INFO - connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
[2025-06-29T10:14:16.361+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-06-29T10:14:16.362+0000] {subprocess.py:93} INFO - 
[2025-06-29T10:14:16.362+0000] {subprocess.py:93} INFO - An error occurred during raw data loading: connection to server at "localhost" (::1), port 5432 failed: Connection refused
[2025-06-29T10:14:16.362+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-06-29T10:14:16.362+0000] {subprocess.py:93} INFO - connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
[2025-06-29T10:14:16.362+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-06-29T10:14:16.363+0000] {subprocess.py:93} INFO - 
[2025-06-29T10:14:16.403+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-29T10:14:16.443+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=amazon_reviews_raw_data_ingestion, task_id=data_loading, execution_date=20250629T101412, start_date=20250629T101415, end_date=20250629T101416
[2025-06-29T10:14:16.484+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-06-29T10:14:16.503+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
