[2025-06-28T13:00:07.003+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: amazon_reviews_raw_data_ingestion.data_loading manual__2025-06-28T13:00:00.269705+00:00 [queued]>
[2025-06-28T13:00:07.009+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: amazon_reviews_raw_data_ingestion.data_loading manual__2025-06-28T13:00:00.269705+00:00 [queued]>
[2025-06-28T13:00:07.010+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-06-28T13:00:07.028+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): data_loading> on 2025-06-28 13:00:00.269705+00:00
[2025-06-28T13:00:07.071+0000] {standard_task_runner.py:57} INFO - Started process 1355 to run task
[2025-06-28T13:00:07.084+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'amazon_reviews_raw_data_ingestion', 'data_loading', 'manual__2025-06-28T13:00:00.269705+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/jet_***_app.py', '--cfg-path', '/tmp/tmp40vtn5bw']
[2025-06-28T13:00:07.097+0000] {standard_task_runner.py:85} INFO - Job 25: Subtask data_loading
[2025-06-28T13:00:07.165+0000] {task_command.py:416} INFO - Running <TaskInstance: amazon_reviews_raw_data_ingestion.data_loading manual__2025-06-28T13:00:00.269705+00:00 [running]> on host a2bf817b2ea7
[2025-06-28T13:00:07.221+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='amazon_reviews_raw_data_ingestion' AIRFLOW_CTX_TASK_ID='data_loading' AIRFLOW_CTX_EXECUTION_DATE='2025-06-28T13:00:00.269705+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-28T13:00:00.269705+00:00'
[2025-06-28T13:00:07.231+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-28T13:00:07.237+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/utils/load_raw_data.py']
[2025-06-28T13:00:07.286+0000] {subprocess.py:86} INFO - Output:
[2025-06-28T13:00:07.452+0000] {subprocess.py:93} INFO - python3: can't open file '/opt/***/utils/load_raw_data.py': [Errno 2] No such file or directory
[2025-06-28T13:00:07.457+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-06-28T13:00:07.486+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-06-28T13:00:07.493+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=amazon_reviews_raw_data_ingestion, task_id=data_loading, execution_date=20250628T130000, start_date=20250628T130007, end_date=20250628T130007
[2025-06-28T13:00:07.522+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 25 for task data_loading (Bash command failed. The command returned a non-zero exit code 2.; 1355)
[2025-06-28T13:00:07.554+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-06-28T13:00:07.725+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
