[2025-06-28T12:50:16.130+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: amazon_reviews_raw_data_ingestion.data-loading scheduled__2025-06-27T00:00:00+00:00 [queued]>
[2025-06-28T12:50:16.138+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: amazon_reviews_raw_data_ingestion.data-loading scheduled__2025-06-27T00:00:00+00:00 [queued]>
[2025-06-28T12:50:16.139+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-06-28T12:50:16.148+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): data-loading> on 2025-06-27 00:00:00+00:00
[2025-06-28T12:50:16.163+0000] {standard_task_runner.py:57} INFO - Started process 1201 to run task
[2025-06-28T12:50:16.168+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'amazon_reviews_raw_data_ingestion', 'data-loading', 'scheduled__2025-06-27T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/jet_***_app.py', '--cfg-path', '/tmp/tmp6guy0k_c']
[2025-06-28T12:50:16.174+0000] {standard_task_runner.py:85} INFO - Job 24: Subtask data-loading
[2025-06-28T12:50:16.390+0000] {task_command.py:416} INFO - Running <TaskInstance: amazon_reviews_raw_data_ingestion.data-loading scheduled__2025-06-27T00:00:00+00:00 [running]> on host a2bf817b2ea7
[2025-06-28T12:50:16.631+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='amazon_reviews_raw_data_ingestion' AIRFLOW_CTX_TASK_ID='data-loading' AIRFLOW_CTX_EXECUTION_DATE='2025-06-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-27T00:00:00+00:00'
[2025-06-28T12:50:16.650+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-28T12:50:16.653+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/utils/load_raw_data.py']
[2025-06-28T12:50:16.692+0000] {subprocess.py:86} INFO - Output:
[2025-06-28T12:50:16.980+0000] {subprocess.py:93} INFO - python: can't open file '/opt/***/utils/load_raw_data.py': [Errno 2] No such file or directory
[2025-06-28T12:50:16.985+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-06-28T12:50:17.034+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-06-28T12:50:17.052+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=amazon_reviews_raw_data_ingestion, task_id=data-loading, execution_date=20250627T000000, start_date=20250628T125016, end_date=20250628T125017
[2025-06-28T12:50:17.079+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 24 for task data-loading (Bash command failed. The command returned a non-zero exit code 2.; 1201)
[2025-06-28T12:50:17.103+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-06-28T12:50:17.175+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
