[2025-06-28T13:17:19.383+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: amazon_reviews_raw_data_ingestion.data_loading manual__2025-06-28T13:17:14.891807+00:00 [queued]>
[2025-06-28T13:17:19.398+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: amazon_reviews_raw_data_ingestion.data_loading manual__2025-06-28T13:17:14.891807+00:00 [queued]>
[2025-06-28T13:17:19.398+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-06-28T13:17:19.412+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): data_loading> on 2025-06-28 13:17:14.891807+00:00
[2025-06-28T13:17:19.432+0000] {standard_task_runner.py:57} INFO - Started process 135 to run task
[2025-06-28T13:17:19.437+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'amazon_reviews_raw_data_ingestion', 'data_loading', 'manual__2025-06-28T13:17:14.891807+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/jet_***_app.py', '--cfg-path', '/tmp/tmp228k93mq']
[2025-06-28T13:17:19.441+0000] {standard_task_runner.py:85} INFO - Job 31: Subtask data_loading
[2025-06-28T13:17:19.479+0000] {task_command.py:416} INFO - Running <TaskInstance: amazon_reviews_raw_data_ingestion.data_loading manual__2025-06-28T13:17:14.891807+00:00 [running]> on host 1d392fc53e17
[2025-06-28T13:17:19.539+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='amazon_reviews_raw_data_ingestion' AIRFLOW_CTX_TASK_ID='data_loading' AIRFLOW_CTX_EXECUTION_DATE='2025-06-28T13:17:14.891807+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-28T13:17:14.891807+00:00'
[2025-06-28T13:17:19.541+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-28T13:17:19.544+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/utils/load_raw_data.py']
[2025-06-28T13:17:19.555+0000] {subprocess.py:86} INFO - Output:
[2025-06-28T13:17:20.676+0000] {subprocess.py:93} INFO - Starting raw data ingestion...
[2025-06-28T13:17:20.688+0000] {subprocess.py:93} INFO - Error connecting to the database: connection to server at "localhost" (::1), port 5432 failed: Connection refused
[2025-06-28T13:17:20.690+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-06-28T13:17:20.690+0000] {subprocess.py:93} INFO - connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
[2025-06-28T13:17:20.690+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-06-28T13:17:20.690+0000] {subprocess.py:93} INFO - 
[2025-06-28T13:17:20.691+0000] {subprocess.py:93} INFO - An error occurred during raw data loading: connection to server at "localhost" (::1), port 5432 failed: Connection refused
[2025-06-28T13:17:20.691+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-06-28T13:17:20.691+0000] {subprocess.py:93} INFO - connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
[2025-06-28T13:17:20.691+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-06-28T13:17:20.691+0000] {subprocess.py:93} INFO - 
[2025-06-28T13:17:20.770+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-28T13:17:20.844+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=amazon_reviews_raw_data_ingestion, task_id=data_loading, execution_date=20250628T131714, start_date=20250628T131719, end_date=20250628T131720
[2025-06-28T13:17:20.892+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-06-28T13:17:20.948+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
